on:
  push:
    branches:
      - feature*

jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-af508dceb67fa9c6e17ec9566e31-prodbucket-c36m8w29po80
    steps:
      - name: chekout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build sight
        run: |
          npm ci
          npm run build
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }} --recursive --acl public-read